#!/opt/perl/bin/perl

use 5.026;

use strict;
use warnings;
no  warnings 'syntax';

use experimental 'signatures';

use Test::More;

my ($program) = grep {-f $_} "solution.pl", "solution";

die "No $program file present" unless $program;

my @inputs = <inp.*>;

foreach my $input (@inputs) {
    SKIP: {
        my $exp = $input =~ s/^inp/exp/r;

        skip "No output file", 1 unless -r $exp;

        my $output   = `perl $program $input`;
        my $expected = `cat  $exp`;

        is $output, $expected, "Test $input";
    }
}

done_testing;

__END__
