#!/opt/perl/bin/perl

use 5.028;

use strict;
use warnings;
no  warnings 'syntax';

use experimental 'signatures';
use experimental 'lexical_subs';

<>;   # Throw away the first line.

while (<>) {
    chomp;
    my ($first, $second) = split ' ';
    say reverse (reverse ($first) + reverse ($second)) =~ s/^0+//r;
}

__END__
